<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>RMDL Assessment 2: Data Analysis Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">RMDL Assessment 2: Data Analysis Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>B288421 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="background" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="background"><span class="header-section-number">1</span> Background</h2>
<ul>
<li><p><em>Instructions are given in italics. You should remove all instructions before submitting</em>.</p></li>
<li><p><em>You MUST include all code and code output in this report. This is a data analysis report, not an essay or journal article.</em></p></li>
</ul>
<p><em>Write a brief literature background for your Stroop task study. Explicitly state your Research Questions and, if available, your Research Hypotheses.</em></p>
<p>The Stroop task, first described by Stroop (1935), is one of the most used paradigms in cognitive psychology. In the classic paradigm, participants are presented with colored words printed in colored ink and asked to name the ink color while ignoring the word itself. The key finding is that participants are slower and less accurate when the word and ink color are incongruent compared to when they are congruent. This difference in reaction time (RT) is known as the Stroop interference effect and is thought to reflect the automaticity of word reading. In other words, because skilled readers process written words automatically, the meaning of the colored word interferes with the identification of its ink color.</p>
<p>The Stroop effect has also been studied in bilingual speakers. <span class="citation" data-cites="MacLeod1991">(<a href="#ref-MacLeod1991" role="doc-biblioref"><strong>MacLeod1991?</strong></a>)</span> reviews approximately two dozen studies on this topic. He notes that a dominant language has greater potential for interference than a nondominant one, and that the pattern of interference shifts as proficiency in the L2 increases. This suggests that the degree of Stroop interference in a given language reflects the extent to which word reading has become automatized in that language. Based on this L1 English speakers, for whom English is the dominant language, are expected to show greater Stroop interference than L2 English speakers.</p>
<section id="research-questionshypotheses" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="research-questionshypotheses"><span class="header-section-number">1.1</span> Research Questions/Hypotheses</h3>
<p><strong>Research questions</strong></p>
<ul>
<li><strong>RQ 1:</strong> Are participants slower when responding to incongruent trials compared to congruent trials?</li>
<li><strong>RQ 2:</strong> Does the Stroop interference effect differ between L1 and L2 English speakers</li>
</ul>
<p><strong>Hypotheses</strong></p>
<ul>
<li><strong>RH 1:</strong> Participants will show slower reaction times on incongruent trials compared to congruent trials, reflecting the Stroop interference.</li>
<li><strong>RH 2:</strong> Since automatic word reading is stronger in a first language, L1 English speakers will show a larger Stroop interference effect compared to L2 English speakers.</li>
</ul>
</section>
</section>
<section id="methods" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="methods"><span class="header-section-number">2</span> Methods</h2>
<p><em>Briefly report the methods of the study (participants, materials, procedure, statistical analysis…). Note that when discussing the statistical analysis you should clearly state how the analysis results will be used to assess the RQs/RHs (be as specific and precise as you can). Include an Open Research/Data availability statement.</em></p>
<section id="participants" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="participants"><span class="header-section-number">2.1</span> Participants</h3>
<p>25 participants took part in the study, and they were divided into L1 English speakers (n = 11) and L2 English speakers (n = 14) based on their self report. Participants were recruited through convenience sampling. No formal exclusion criteria were applied.</p>
</section>
<section id="materials" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="materials"><span class="header-section-number">2.2</span> Materials</h3>
<p>The experiment was designed and administered using Testable. The stimuli consisted of three color words (RED, BLUE, and GREEN) presented in colored ink (red, blue, or green). Each word appeared in either a congruent condition (word and ink color match) or an incongruent condition (word and ink color do not match). Each block contained 20 critical trials (10 congruent, 10 incongruent) and 12 filler trials consisting of non-color words (CAR, SHOE, HOUSE) presented in colored ink.</p>
</section>
<section id="procedure" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="procedure"><span class="header-section-number">2.3</span> Procedure</h3>
<p>Participants completed the experiment online via Testable. They were instructed to respond to the ink color of the word by pressing the LEFT arrow key for red, the UP arrow key for blue, and the RIGHT arrow key for green as quickly and accurately as possible. Following the experimental trials, participants completed a short questionnaire asking whether English was their first language, their self-rated English proficiency, and whether they currently reside in an English-speaking country.</p>
</section>
<section id="statistical-analysis" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="statistical-analysis"><span class="header-section-number">2.4</span> Statistical analysis</h3>
<p>Data were analyzed using Bayesian multilevel modeling in R (brms). Only critical trials were retained, and RT outliers were removed (RT &lt; 200ms or &gt; 2000ms). A model was fitted with log RT as the outcome, with congruency, English language status, and their interaction as fixed effects, and varying intercepts and slopes for congruency by participant. The main effect of congruency was used to assess whether a Stroop effect was present, and the interaction term was used to assess whether the Stroop effect differed between L1 and L2 speakers.</p>
</section>
<section id="open-research-statement" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="open-research-statement"><span class="header-section-number">2.5</span> Open research statement</h3>
<p>The experimental trial file, raw data, and analysis code are available at [link to Github]. The experiment was administered via Testable and can be accessed at [<a href="https://tstbl.co/661-427" class="uri">https://tstbl.co/661-427</a>].</p>
</section>
</section>
<section id="data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data"><span class="header-section-number">3</span> Data</h2>
<p><em>Remember to include all code and code output in the submission.</em></p>
<section id="read-and-process-the-data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="read-and-process-the-data"><span class="header-section-number">3.1</span> Read and process the data</h3>
<p><em>Read the data here. If the data needs processing, like mutating columns or creating new ones, briefly explain why processing is needed and what you did</em>. <em>Include a description of each of the relevant columns in the data.</em> The data was downloaded from Testable in long format, with all 25 participants’ trial results combined into a single CSV file. The file was read into R using read_csv().</p>
<p>Several processing steps were applied to prepare the data for analysis. First, each participant’s response to the question “Is English your first language?” (row 82 in the trial file) was extracted and used to create a new column <strong>l1_status</strong>, coded as <strong>L1</strong> for participant who answered “Yes” and <strong>L2</strong> for all other responses. This column identified the between-subjects grouping variable for the analysis.</p>
<p>The data was then filtered to retain only critical test trials (<strong>condition1 == “critical”</strong>), excluding practice and filler trials that are not relevant to the research question. RT outliers were removed, excluding trials with RT below 200ms (anticipatory responses) or above 2000ms (inattentive responses).</p>
<p>The relevant columns in the cleaned dataset are as follows:</p>
<ul>
<li><strong>filename:</strong> unique identifier for each participant, based on their Testable result file</li>
<li><strong>condition2:</strong> the congruency condition of each trial</li>
<li><strong>RT:</strong> reaction time in milliseconds, measured from stimulus onset to key press</li>
<li><strong>correct:</strong> accuracy of the responses, coded as 1 (correct) or 0 (incorrect)</li>
<li><strong>l1_status:</strong> English language status of the participant, coded as L1 (English is their first language) or L2 (English is not their first language)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read raw data file</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/661427_260428_102656_long.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2025 Columns: 38
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (23): filename, browser, version, OS, OS_lang, GMT_timestamp, local_time...
dbl (15): screenWidth, screenHeight, duration_s, duration, duration_m, rowNo...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#extract rowNo 82 (L1 question) for each participant</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>l1_info <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rowNo <span class="sc">==</span> <span class="dv">82</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(filename, <span class="at">l1_response =</span> response)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#merge l1_info and create english_status column</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 'Yes' = L1 English, anything else = L2</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(l1_info, <span class="at">by =</span> <span class="st">'filename'</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">l1_status =</span> <span class="fu">ifelse</span>(l1_response <span class="sc">==</span> <span class="st">'Yes'</span>, <span class="st">'L1'</span>, <span class="st">'L2'</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">#filter for critical trials and select relevant columns </span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> raw <span class="sc">|&gt;</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(type <span class="sc">==</span> <span class="st">'test'</span>, condition1 <span class="sc">==</span> <span class="st">'critical'</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(filename, stim1, textColor, condition2, RT, correct, l1_status) <span class="sc">|&gt;</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">condition2 =</span> <span class="fu">factor</span>(condition2, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'congruent'</span>, <span class="st">'incongruent'</span>)),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">l1_status =</span> <span class="fu">factor</span>(l1_status, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'L1'</span>, <span class="st">'L2'</span>))</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RT <span class="sc">&gt;</span> <span class="dv">200</span>, RT <span class="sc">&lt;</span> <span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-the-data" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="plot-the-data"><span class="header-section-number">3.2</span> Plot the data</h3>
<p><em>Create relevant plots: for each, include a description of the plot (type, axes, colours used and so on) and a description of relevant patterns.</em></p>
<p><strong>Plot 1: RT distribution</strong></p>
<p>This is a density plot showing the distribution of log-transformed reaction times across congruency conditions, faceted by L1_status. The x-axis shows log RT and the y-axis shows density. Congruency donition is indicated by fill color, with congruent trials shown in pink and incongruent trials shown in teal. The left panel shows L1 English speakers and the right panel shows L2 English speakers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot1: RT distribution by congruency and L1_status</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(RT),<span class="at">fill=</span>condition2)) <span class="sc">+</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>l1_status) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">'Distribution of log RT by congruency and L1 status'</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'log RT'</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">'Congruency'</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In both panels, the incongruent distribution is shifted rightward relative to the congruent distribution, indicating that participants were generally slower on incongruent trials regardless of language background, and this is consistent with a Stroop interference effect. The shift appears visually larger in the L1 panel compared to the L2 panel, suggesting that the interference effect may be greater for L1 English speakers.</p>
<p><strong>Plot 2: Mean log RT</strong></p>
<p>This is a point plot showing mean log-transformed reaction time for each congruency condition, with congruency on the x-axis and mean log RT on the y-axis. L1 status is indicated by color, with L1 speakers shown in pink and L2 speakers in teal. Error bars represent one standard deviation above and below the mean log RT. Points for the same L1 status group are connected by a line to make the congruency effect easier to follow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot2: mean log RT by congruency and english_status</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(l1_status,condition2) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_logRT =</span> <span class="fu">mean</span>(<span class="fu">log</span>(RT)),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_logRT =</span> <span class="fu">sd</span>(<span class="fu">log</span>(RT))</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> condition2, <span class="at">y =</span> mean_logRT,<span class="at">color =</span> l1_status, <span class="at">group =</span> l1_status)) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_logRT <span class="sc">-</span> sd_logRT,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean_logRT <span class="sc">+</span> sd_logRT),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">'Mean log RT by congruency and L1 status'</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'Congruency'</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">'Mean log RT'</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">'L1 status'</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'l1_status'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both groups show a clear increase in mean log RT from congruent to incongruent trials, consistent with a Stroop interference effect in both L1 and L2 English speakers. The slow of the increase appears steeper for L1 speakers than L2 speakers, suggesting a larger congruency effect for the L1 group, which is consistent with the predicted direction. L2 speakers show higher overall log RT in both conditions, suggesting they are generally slower to respond. The error bars overlap substantially between groups, reflecting considerable variability across participants, which is expected given the relatively small sample size.</p>
<p><strong>Plot 3: Accuracy</strong></p>
<p>This is a bar plot showing the mean accuracy for each combination of congruency condition and L1 status. Congruency is shown on the x-axis and mean accuracy on the y-axis, ranging from 0 to 1. L1 status is indicated by fill color, with L1 speakers in pink and L2 speakers in teal. Bars for each group are displayed side by side within each congruency condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot3: accuracy by congruency and L1 status</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(l1_status,condition2) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_acc =</span> <span class="fu">mean</span>(correct)) <span class="sc">|&gt;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> condition2,<span class="at">y =</span> mean_acc,<span class="at">fill =</span> l1_status)) <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">'dodge'</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">'Accuracy by congruency and L1 status'</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">'Congruency'</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">'Mean accuracy'</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">'L1 status'</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'l1_status'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Accuracy is uniformly high across all conditions, with all bars approaching 1.0, indicating a ceiling effect. A small decrease in accuracy is visible from congruent to incongruent trials in both groups, consistent with the expected direction of a Stroop interference effect. The difference between L1 and L2 speakers within each congruency condition is minimal.</p>
</section>
<section id="summarize-the-data" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="summarize-the-data"><span class="header-section-number">3.3</span> Summarize the data</h3>
<p><em>Calculate and report appropriate summary measures for relevant variables in the data.</em> The table below reports mean RT, SD of RT, mean log RT, SD of log RT, mean accuracy, and number of trials for each combination of congruency condition and L1 status groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> cleaned_data <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(l1_status,condition2) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_RT =</span> <span class="fu">mean</span>(RT),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_RT =</span> <span class="fu">sd</span>(RT),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_logRT =</span> <span class="fu">mean</span>(<span class="fu">log</span>(RT)),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_logRT =</span> <span class="fu">sd</span>(<span class="fu">log</span>(RT)),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">accuracy =</span> <span class="fu">mean</span>(correct),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_trials =</span> <span class="fu">n</span>()</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'l1_status'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>summary_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
# Groups:   l1_status [2]
  l1_status condition2  mean_RT sd_RT mean_logRT sd_logRT accuracy n_trials
  &lt;fct&gt;     &lt;fct&gt;         &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;int&gt;
1 L1        congruent      607.  238.       6.35    0.331    0.961      258
2 L1        incongruent    742.  314.       6.53    0.390    0.945      255
3 L2        congruent      677.  256.       6.46    0.327    0.973      328
4 L2        incongruent    770.  301.       6.58    0.361    0.941      321</code></pre>
</div>
</div>
<p>L1 English speakers showed a mean RT of 607ms on congruent trials and 742ms on incongruent trials, reflecting a Stroop interference effect of approximately 134ms. L2 English speakers showed a mean RT of 677ms on congruent trials and 770ms on incongruent trials, reflecting a small interference effect of approximately 94ms. Both groups show the expected pattern of slower response on incongruent trials. The Stroop effect appears numerically larger for L1 speakers than L2 speakers, consistent with the predicted direction. Accuracy was high across all conditions, exceeding 0.94 in all groups, indicating a ceiling effect.</p>
</section>
</section>
<section id="regression-modelling" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="regression-modelling"><span class="header-section-number">4</span> Regression modelling</h2>
<p><em>Write an explanation of the regression model(s) you will run to answer the chosen research question. Fit the model and get a model summary and relevant model plots. Report the results of the model.</em> To investigate whether L1 status modulates the Stroop interference effect, a Bayesian multilevel model was fitted using the brms package in R. Log-transformed reaction time was used as the outcome variable, with a Gaussian family. The model included congruency (congruent vs.&nbsp;incongruent), English status (L1, vs.&nbsp;L2), and their interaction as fixed effects.</p>
<p>The interaction term is of primary interest, as it tests whether the size of the Stroop effect differs between L1 and L2 English speakers. Varying intercepts and varying slopes for congruency were included by participant, allowing baseline RT and the congruency effect to differ across individuals. Default weakly informative priors were used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Rcpp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading 'brms' package (version 2.23.0). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'brms'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    ar</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>rt_bm <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(RT) <span class="sc">~</span> condition2 <span class="sc">*</span> l1_status <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> condition2 <span class="sc">|</span> filename),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> gaussian,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> cleaned_data,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cores =</span> <span class="dv">4</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"data/cache/rt_bm"</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rt_bm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian 
  Links: mu = identity 
Formula: log(RT) ~ condition2 * l1_status + (1 + condition2 | filename) 
   Data: cleaned_data (Number of observations: 1162) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Multilevel Hyperparameters:
~filename (Number of levels: 25) 
                                     Estimate Est.Error l-95% CI u-95% CI Rhat
sd(Intercept)                            0.15      0.03     0.10     0.21 1.00
sd(condition2incongruent)                0.05      0.03     0.00     0.11 1.00
cor(Intercept,condition2incongruent)     0.43      0.40    -0.52     0.97 1.00
                                     Bulk_ESS Tail_ESS
sd(Intercept)                            1468     2194
sd(condition2incongruent)                1033      903
cor(Intercept,condition2incongruent)     2014     1762

Regression Coefficients:
                                  Estimate Est.Error l-95% CI u-95% CI Rhat
Intercept                             6.35      0.05     6.25     6.45 1.00
condition2incongruent                 0.18      0.03     0.12     0.25 1.00
l1_statusL2                           0.11      0.07    -0.03     0.24 1.00
condition2incongruent:l1_statusL2    -0.06      0.05    -0.15     0.03 1.00
                                  Bulk_ESS Tail_ESS
Intercept                             1227     1968
condition2incongruent                 2668     2765
l1_statusL2                           1217     2024
condition2incongruent:l1_statusL2     2610     2534

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     0.32      0.01     0.31     0.33 1.00     4987     2817

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>The intercept represents the estimated baseline log RT for L1 English speakers on congruent trials (6.35, 95% CrI[6.25, 6.45]). The main effect of congruency for L1 speakers was 0.18 log RT units (95% CrI [0.12, 0.25]), indicating that incongruent trials were credible slower than congruent trials, as the 95% CrI excludes 0, providing clear evidence of a Stroop interference effect in L1 English speakers. L2 speakers were estimated to be slightly slower overall than L1 speakers (0.11, 95% CrI[-0.02, 0.24]), though this difference was not conclusive as the CrI includes 0.</p>
<p>The interaction term between congruency and English status (-0.06, 95% CrI[-0.15, 0,.03]) is of primary interest because it tests whether the Stroop effect differs between groups. The negative estimate indicates that L2 speakers show a smaller Stroop interference effect than L1 speakers, consistent with the predicted direction. However, the 95% CrI includes 0, meaning that there is no conclusive evidence that the two groups differ in the magnitude of the Stroop effect. The random effect indicates meaningful variaility in baseline RT across participants (sd(Intercept) = 0.15), confirming that individuals differ in their overall response speed, while variability in the Stroop effect across participants was small (sd(condition2incongruent) = 0.05).</p>
<section id="model-plots" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="model-plots"><span class="header-section-number">4.1</span> Model plots</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conditional_effects</span>(rt_bm, <span class="st">'condition2:l1_status'</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">points =</span> <span class="cn">FALSE</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both groups show an increase in model-estimated log RT from congruent to incongruent trials, consistent with a Stroop interference effect in both L1 and L2 English speakers. The increase appears slightsly larger for L1 speakers than L2 speakers, reflecting the numerically larger interference effect observed in the model coefficients. The credible intervals overlap substantially between groups, particularly on incongruent trials, which is consistent with teh interaction term whose 95% CrI included 0, indicating uncertainty about whether the groups genuinely differ in the magnitude of the Stroop effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>rt_draws <span class="ot">&lt;-</span> <span class="fu">as_draws_df</span>(rt_bm, <span class="st">'^b'</span>, <span class="at">regex =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>rt_draws <span class="ot">&lt;-</span> rt_draws <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">stroop_L1 =</span> b_condition2incongruent,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">stroop_L2 =</span> b_condition2incongruent <span class="sc">+</span> <span class="st">`</span><span class="at">b_condition2incongruent:l1_statusL2</span><span class="st">`</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">group_difference =</span> stroop_L2 <span class="sc">-</span> stroop_L1</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>rt_stroop_diff <span class="ot">&lt;-</span> rt_draws <span class="sc">|&gt;</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(stroop_L1, stroop_L2, group_difference) <span class="sc">|&gt;</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Dropping 'draws_df' class as required metadata was removed.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>rt_stroop_diff <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(value, <span class="at">fill =</span> name)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rt_stroop_diff <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">q5  =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.05</span>), <span class="dv">3</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">q10 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.10</span>), <span class="dv">3</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">q20 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.20</span>), <span class="dv">3</span>),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">q80 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.80</span>), <span class="dv">3</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">q90 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.90</span>), <span class="dv">3</span>),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">q95 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(value, <span class="fl">0.95</span>), <span class="dv">3</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  name                 q5    q10    q20    q80    q90   q95
  &lt;chr&gt;             &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 group_difference -0.136 -0.119 -0.099 -0.024 -0.004 0.013
2 stroop_L1         0.128  0.142  0.157  0.211  0.226 0.238
3 stroop_L2         0.074  0.084  0.098  0.146  0.16  0.172</code></pre>
</div>
</div>
<p>The Stroop effect for L1 English speakers was credibly positive, with a 90% CrI of [0.142, 0.226] and a 95% CrI of [0.128, 0.238], both excluding 0. This provides clear evidence of a Stroop interference effect in L1 English speakers. Similarly, the Stroop effect for L2 English speakers was also credibly positive, with a 90% CrI of [0.084, 0.160] and 95% CrI of [0.074, 0.172], both excluding 0, indicating a Stroop interference effect in L2 English speakers as well.</p>
<p>For the group difference, the 90% of CrI is [-0.119, -0.004], which excludes 0, suggesting that at 90% probability the Stroop effect is smaller for L2 speakers than L2 speakers. However, the 95% CrI [-0.136, 0.013] includes 0, indicating uncertainty about whether the groups genuinely differ at 95% confidence. The results are therefore inconclusive as to whether English language status modulates the Stroop interference, though the direction of the difference is consistent with the prediction than L1 English speakers show greater interference than L2 English speakers.</p>
</section>
</section>
<section id="discussion" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="discussion"><span class="header-section-number">5</span> Discussion</h2>
<p><em>Write a brief discussion of the your model results in light of the research question.</em></p>
<p>The results provided clear evidence in support of RH 1. Both L1 and L2 English speakers showed credibly slower reaction times on incongruent trials than congruent trials, with the Stroop effect for L1 speakers estimated at 0.18 log RT units (95% CrI [0.128, 0.238]) and for L2 speakers at 0.12 log RT units (95% CrI[0.04, 0.172]). This is consistent with the well-established Stroop interference effect, whereby the automatic reading of a colored word interferes with the identification of its ink color.</p>
<p>With respect RQ 2, the results were inconclusive. The group difference was in the predicted direction, with L1 English speakers showing a numerically larger Stroop effect than L2 English speakers, and the 90% CrI for the difference excluded 0 [-0.119, -0.004], providing weak evidence consistent with RH 2. However, the 95% CrI included 0 [-0.136, 0.013], meaning the data are also compatible with no group difference. This inconclusiveness can likely be attributed in part to the small sample size, which limits the precision of the estimates. Futuer research with larger samples would be needed to draw more definitely conclusions about whether English language status modulates the Stroop interference effect.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>